with source as (
    select * from {{ source('datafreedom', 'df_global_property') }}
)

select 
    voyager_url,
    type,
    tax_authority,
    state,
    source_data_through,
    property_id,
    postal_code,
    notes,
    name,
    longitude,
    legal_entity_name,
    legal_entity_id,
    legal_entity_code,
    latitude,
    is_residential,
    is_commercial,
    is_active,
    inactive_date,
    database_id,
    country,
    code,
    city,
    base_currency,
    attribute___state_registered,
    attribute___state,
    attribute___region,
    attribute___property_type,
    attribute___fund,
    attribute___dm_property_type,
    attribute___dm_property_manager,
    attribute___dm_leasing_manager,
    attribute___dm_lease_renewal_rep,
    attribute___dm_asset_manager,
    attribute___dm_am_approver,
    area___net_rent,
    area___net_lease,
    area___gross_rent,
    area___gross_lease,
    area___default__sum_of_units_,
    area___default,
    address_2,
    address_1
from source
where code <> 'donotuse'